#!/usr/bin/env bash
# Emit a self-contained installer script the user can run on their Mac.
# Use this when Claude is in a credentials-less sandbox (Cowork) and cannot
# push to GitHub directly. The generated script installs the skill to
# Claude Code AND pushes to the marketplace in one run on the user's host.
#
# Usage: bash generate-installer.sh <skill-folder> <repo-url> <plugin-folder> [<output-path>]
# Default output: ~/Projects/install-<skill-name>.sh

set -euo pipefail

SKILL_PATH="${1:-}"
REPO_URL="${2:-}"
PLUGIN_FOLDER="${3:-}"
OUT_PATH="${4:-}"

[[ -n "$SKILL_PATH" && -n "$REPO_URL" && -n "$PLUGIN_FOLDER" ]] || {
  echo "ERROR: usage: generate-installer.sh <skill-folder> <repo-url> <plugin-folder> [<output-path>]"
  exit 2
}
SKILL_PATH="${SKILL_PATH/#\~/$HOME}"

[[ -f "$SKILL_PATH/SKILL.md" ]] || { echo "ERROR: $SKILL_PATH/SKILL.md missing"; exit 1; }
SKILL_NAME=$(awk '/^name: /{print $2; exit}' "$SKILL_PATH/SKILL.md" | tr -d '"'"'"'')
SKILL_DESC=$(awk 'BEGIN{desc=""} /^description: /{sub(/^description: /, ""); desc=$0} END{gsub(/^["'"'"']|["'"'"']$/, "", desc); print desc}' "$SKILL_PATH/SKILL.md")

# Make the source path portable: if it's under $HOME, substitute $HOME
PORTABLE_SRC="$SKILL_PATH"
if [[ "$SKILL_PATH" == "$HOME/"* ]]; then
  PORTABLE_SRC="\$HOME/${SKILL_PATH#$HOME/}"
fi

OUT_PATH="${OUT_PATH:-$HOME/Projects/install-${SKILL_NAME}.sh}"
OUT_PATH="${OUT_PATH/#\~/$HOME}"
mkdir -p "$(dirname "$OUT_PATH")"

cat > "$OUT_PATH" <<INSTALLER
#!/usr/bin/env bash
# Auto-generated by skill-deployer on $(date '+%Y-%m-%d %H:%M:%S')
# Installs '$SKILL_NAME' to Claude Code AND pushes to $REPO_URL.
# Run once on the Mac where your git credentials live.

set -euo pipefail

SRC="$PORTABLE_SRC"
SKILL_NAME="$SKILL_NAME"
REPO_URL="$REPO_URL"
PLUGIN_FOLDER="$PLUGIN_FOLDER"
TS=\$(date +%Y%m%d-%H%M%S)

[[ -d "\$SRC" ]] || { echo "ERROR: source not found at \$SRC"; exit 1; }
[[ -f "\$SRC/SKILL.md" ]] || { echo "ERROR: \$SRC/SKILL.md missing"; exit 1; }

# --- 1. Claude Code -----------------------------------------------------------
echo ">>> [1/2] Installing to Claude Code (~/.claude/skills/\$SKILL_NAME)"
mkdir -p "\$HOME/.claude/skills"
cd "\$HOME/.claude/skills"
if [[ -d "\$SKILL_NAME" ]]; then
  mv "\$SKILL_NAME" "\${SKILL_NAME}.bak.\$TS"
  echo "    archived: ~/.claude/skills/\${SKILL_NAME}.bak.\$TS"
fi
rsync -a \\
  --exclude='__pycache__' --exclude='.pytest_cache' \\
  --exclude='pytest-cache-files-*' --exclude='.DS_Store' --exclude='node_modules' \\
  "\$SRC/" "\$HOME/.claude/skills/\$SKILL_NAME/"
echo "    installed (\$(find "\$HOME/.claude/skills/\$SKILL_NAME" -type f | wc -l | tr -d ' ') files)"

# --- 2. Marketplace repo ------------------------------------------------------
echo ""
echo ">>> [2/2] Updating marketplace repo: \$REPO_URL"
REPO_NAME=\$(basename "\$REPO_URL" .git)
CLONE_DIR="\$HOME/Downloads/\${REPO_NAME}-update-\$TS"
git clone "\$REPO_URL" "\$CLONE_DIR"
cd "\$CLONE_DIR"

[[ -d "\$PLUGIN_FOLDER" ]] || { echo "ERROR: plugin folder '\$PLUGIN_FOLDER' not in repo"; exit 1; }

SKILL_DEST="\$PLUGIN_FOLDER/skills/\$SKILL_NAME"
CMD_DEST="\$PLUGIN_FOLDER/commands/\$SKILL_NAME.md"
REPLACED=0
[[ -d "\$SKILL_DEST" ]] && { git rm -rf "\$SKILL_DEST" >/dev/null; REPLACED=1; }
[[ -f "\$CMD_DEST" ]] && git rm "\$CMD_DEST" >/dev/null || true

mkdir -p "\$PLUGIN_FOLDER/skills" "\$PLUGIN_FOLDER/commands"
rsync -a \\
  --exclude='__pycache__' --exclude='.pytest_cache' \\
  --exclude='pytest-cache-files-*' --exclude='.DS_Store' --exclude='node_modules' \\
  "\$SRC/" "\$SKILL_DEST/"

cat > "\$CMD_DEST" <<CMD
---
description: ${SKILL_DESC//\"/\\\"}
argument-hint: "<arguments for \$SKILL_NAME>"
---

# /\$SKILL_NAME

${SKILL_DESC//\`/\\\`}

## Invocation

\\\`\\\`\\\`
/\$SKILL_NAME <your arguments>
\\\`\\\`\\\`

## Workflow

Load the \\\`\$SKILL_NAME\\\` skill and follow its SKILL.md workflow.
CMD

# Quote any unquoted argument-hint values in existing command files.
# YAML parses bare '<...>' as a type tag, which Claude.ai's marketplace
# validator rejects. Our generated command files already quote correctly,
# but pre-existing files in the repo may not.
python3 - "\$PLUGIN_FOLDER" <<'PY'
import pathlib, re, sys
plugin_folder = sys.argv[1]
cmd_dir = pathlib.Path(plugin_folder) / "commands"
if cmd_dir.is_dir():
    pat = re.compile(r'^(argument-hint:)[ \t]*(.+?)[ \t]*$', re.MULTILINE)
    for md in sorted(cmd_dir.glob("*.md")):
        text = md.read_text()
        def _q(m):
            key, val = m.group(1), m.group(2)
            if val.startswith('"') or val.startswith("'"):
                return m.group(0)
            val_esc = val.replace('"', '\\\\"')
            return f'{key} "{val_esc}"'
        new = pat.sub(_q, text)
        if new != text:
            md.write_text(new)
            print(f"quoted argument-hint: {md}")
PY

# Align versions across marketplace.json and plugin.json, then bump patch.
python3 - "\$PLUGIN_FOLDER" <<'PY'
import json, pathlib, sys
plugin_folder = sys.argv[1]
def parse(v):
    try: return tuple(int(x) for x in v.split("."))
    except Exception: return (0, 0, 0)
mp = pathlib.Path(".claude-plugin/marketplace.json")
pl = pathlib.Path(plugin_folder) / ".claude-plugin" / "plugin.json"
paths = [p for p in (mp, pl) if p.exists()]
if paths:
    hi = max(parse(json.loads(p.read_text()).get("version", "0.0.0")) for p in paths)
    new = f"{hi[0]}.{hi[1]}.{hi[2] + 1}"
    for p in paths:
        d = json.loads(p.read_text())
        old = d.get("version", "")
        d["version"] = new
        p.write_text(json.dumps(d, indent=2) + "\n")
        print(f"bumped {p}: {old} -> {new}")
PY

# Pre-push YAML validation — abort if any frontmatter is malformed.
python3 - "\$PLUGIN_FOLDER" <<'PY'
import pathlib, re, sys
try:
    import yaml
except ImportError:
    print("NOTE: PyYAML not installed; skipping strict YAML pre-push validation.")
    sys.exit(0)
plugin_folder = sys.argv[1]
root = pathlib.Path(plugin_folder)
errors = []
for p in list(root.glob("commands/*.md")) + list(root.glob("skills/*/SKILL.md")):
    text = p.read_text()
    m = re.match(r'^---\s*\n(.*?)\n---\s*\n', text, re.DOTALL)
    if not m:
        errors.append(f"  MISSING FRONTMATTER: {p}")
        continue
    try:
        fm = yaml.safe_load(m.group(1))
        if not isinstance(fm, dict):
            errors.append(f"  FRONTMATTER NOT A MAPPING: {p}")
    except yaml.YAMLError as e:
        errors.append(f"  YAML PARSE ERROR: {p}: {e}")
if errors:
    print("\n".join(errors))
    print("\nABORTING push — fix frontmatter above.")
    sys.exit(1)
print("frontmatter validated")
PY

git add -A
ACTION="Add"
[[ "\$REPLACED" -eq 1 ]] && ACTION="Update"
git -c commit.gpgsign=false commit -m "\$ACTION skill: \$SKILL_NAME

Deployed via skill-deployer."

DEFAULT_BRANCH=\$(git symbolic-ref refs/remotes/origin/HEAD 2>/dev/null | sed 's@^refs/remotes/origin/@@' || echo "main")
git push origin "HEAD:\$DEFAULT_BRANCH"

echo ""
echo "=== DONE ==="
echo "  Claude Code: restart Claude Code to pick up /\$SKILL_NAME"
echo "  Cowork:      reinstall marketplace plugin (Settings -> Plugins -> Update)"
echo "  Clone used:  \$CLONE_DIR (safe to delete)"
INSTALLER

chmod +x "$OUT_PATH" 2>/dev/null || true
echo "Generated installer: $OUT_PATH"
echo "Tell the user to run: bash $OUT_PATH"
